version: '2'
services:
  backend:
    build: ./
    ports:
      - 4000:4000
    links:
      - db
    volumes:
      - ./:/opt/app
    tty: true
    environment:
      TERM: xterm-color

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "drowsy_dev"

